name: 'izuna-action'
description: 'Run izuna'
inputs:
  owner:
    description: 'Owner of the repository'
    required: true
  repository:
    description: 'Name of the repository'
    required: true
  package:
    description: 'Name of the package'
    required: true
  ghcVersion:
    description: 'Version of Ghc used'
    required: true
  hieDirectory:
    description: 'Where the hie files are stored'
    required: true
    default: '.hie'
runs:
  using: 'node12'
  main: 'dist/index.js'
