name: 'izuna-action'
description: 'Run izuna'
inputs:
  packageName:
    description: 'Name of the package'
    required: true
    default: 'World'
  ghcVersion:
    description: 'Version of Ghc used'
    required: true
    default: 'World'
runs:
  using: 'node12'
  main: 'index.js'
