name: 'izuna-action'
description: 'Run izuna'
inputs:
  packageName:
    description: 'Name of the package'
    required: true
    default: 'World'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'index.js'
