name: 'izuna-action'
description: 'Run izuna'
inputs:
  ghcVersion:
    description: 'Version of Ghc used. Must be one of: 8.10.1, 8.10.2, 8.10.3'
    required: true
  hieDirectory:
    description: 'Where the hie files are stored (usually `./.hie/` for regular projects)'
    required: true
  projectRoot:
    description: 'Where your project is stored (usually `.` for regular projects)'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
